### ISSUE TITLE
Customizing issue comment

### ISSUE THREAD

**Issue by muryoh** [tech-advantage/sonar-gerrit-plugin#35]
Hi and thanks for this plugin. It works really well

Would you accept a PR for customizing review comments?
They currently are quite technical and I think they could be enhanced, for example by adding HTML links to the sonar rule on the sonar server.

My idea would be to make the message configurable by using some kind of variable substitution mechanism.

**Comment by muryoh** [comment]
Currently, the formatting of an issue comment is:
`"[%s] New: %s Severity: %s, Message: %s"`

The new default would be something like
`"[${issue.isNew}] New: ${issue.ruleKey} Severity: ${issue.severity}, Message: ${issue.message}"`

It would allow the link thing I mentioned. That message could therefore be configured and allow something like
`"[${issue.ruleKey}](${sonar.serverUrl}/coding_rules#rule_key=${issue.ruleKey}), ${issue.severity}: ${issue.message}"`

That would result in:

[pmd:AvoidBranchingStatementAsLastInLoop](http://sonar/coding_rules#rule_key=pmd:AvoidBranchingStatementAsLastInLoop), major: Avoid Branching Statement As Last In Loop

The big idea is that rules are not always explicit and it's very nice to be able to go to a link describing the issue directly

**Comment by mildis** [comment]
Hi @muryoh,

We are accepting PR as long as they do not break any existing features and that you could maintain the introduced features.

**Comment by mildis** [comment]
@muryoh Does something like [this code](https://github.com/tech-advantage/sonar-gerrit-plugin/compare/master...mildis:issue_substitution?w=1) is what you think about ?
Note that I’m not sure that Gerrit knows how to interpret Markdown-like syntax to create link.

**Comment by muryoh** [comment]
Yes, it's exactly this kind of feature.
I stumbled into it when I started to look in the code.

Gerrit knows depending on the configuration. The Gerrit we use at ULLINK
does, I believe it does through regexp replaces.

**Comment by muryoh** [comment]
Created a PR for it: https://github.com/tech-advantage/sonar-gerrit-plugin/pull/36

Let me know if it's OK for you - I can do it for alerts too to have consistency
