### ISSUE TITLE
Issues found but still Sonar-Gerrit still sends +1

### ISSUE THREAD

**Issue by saadlu** [tech-advantage/sonar-gerrit-plugin#41]
It was all working fine, but now no more.

So, on the Jenkins Job, after the build that runs sonarqube, I have a "Post-build Actions",  "Post SonarQube issues as Gerrit Commnents"

When the job is done, I see on the console output:

  ```
Getting Sonar Report from: /home/mashrurm/.jenkins/jobs/test-again/workspace/build/sonar/report.json
Report has loaded and contains 1 issues
Connected to Gerrit: server name: gWAPPs gerrit. Change Number: 8, PatchSetNumber: 1
Review has been sent
```

But on the Gerrit side, I see

```
Patch Set 1:
SonarQube violations have not been found.
```

And a +1 vote on the label (I have Sonar-Verified setup).

Funny thing is that it all worked perfectly first time I did it.

**Comment by saadlu** [comment]
My Bad.

I needed to uncheck "Add comments to changed lines only"

**Comment by ontheway01** [comment]
I have the same problem.I am sure **unchecking Add comments to changed lines only**.it all failed first time I did it.
