### ISSUE TITLE
Knowhosts for ssh connection

### ISSUE THREAD

**Issue by walthhy** [tech-advantage/sonar-gerrit-plugin#42]
We're using this in container env of jenkins pipeline,
the issue is related to hostkey in known_hosts. We'll get different error for different scenario. Pls see following for details. 

My workaround is download a good known_hosts file from another server.
Yes. we can add this file into containers, but it's not flexible. Can we do some enhancement that can add new hostkey into known_hosts without failing it?

If no known_hosts. we'll get following error:
[SonarQube] 06:40:08.130 DEBUG: Executing command 'gerrit review 7675590f782b5042674fdabd6b7e2da62f98ac4b -j' on UserAtHost@1a1ed4e5 [user=xxx, host=xxxx, port=29418] (stdin = 69 bytes)
[SonarQube] 06:40:08.137 INFO: ------------------------------------------------------------------------
[SonarQube] 06:40:08.137 INFO: EXECUTION FAILURE
[SonarQube] 06:40:08.137 INFO: ------------------------------------------------------------------------
[SonarQube] 06:40:08.137 INFO: Total time: 13.460s
[SonarQube] 06:40:08.230 INFO: Final Memory: 57M/641M
[SonarQube] 06:40:08.230 INFO: ------------------------------------------------------------------------
[SonarQube] 06:40:08.230 ERROR: Error during SonarQube Scanner execution
[SonarQube] java.lang.IllegalStateException: Unable to load component class org.sonar.batch.scan.ImmutableProjectReactor
[SonarQube] 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:69)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
[SonarQube] 	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
[SonarQube] 	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
[SonarQube] 	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
[SonarQube] 	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
[SonarQube] 	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
[SonarQube] 	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
[SonarQube] 	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
[SonarQube] 	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
[SonarQube] 	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
[SonarQube] 	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.instantiateComponentAsIsStartable(DefaultPicoContainer.java:1034)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.addAdapterIfStartable(DefaultPicoContainer.java:1026)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1003)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
[SonarQube] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:141)
[SonarQube] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
[SonarQube] 	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
[SonarQube] 	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
[SonarQube] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
[SonarQube] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
[SonarQube] 	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
[SonarQube] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
[SonarQube] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
[SonarQube] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[SonarQube] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[SonarQube] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[SonarQube] 	at java.lang.reflect.Method.invoke(Method.java:498)
[SonarQube] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[SonarQube] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
[SonarQube] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
[SonarQube] 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
[SonarQube] 	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
[SonarQube] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
[SonarQube] 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
[SonarQube] Caused by: fi.jpalomaki.ssh.SshClientException: Failed to execute command 'gerrit review 7675590f782b5042674fdabd6b7e2da62f98ac4b -j' on UserAtHost@1a1ed4e5 [user=xxx, host=xxxx, port=29418]
[SonarQube] 	at fi.jpalomaki.ssh.jsch.JschSshClient.executeCommand(JschSshClient.java:77)
[SonarQube] 	at fr.techad.sonar.gerrit.GerritSshConnector.setReview(GerritSshConnector.java:56)
[SonarQube] 	at fr.techad.sonar.gerrit.GerritSshFacade.setReview(GerritSshFacade.java:46)
[SonarQube] 	at fr.techad.sonar.GerritProjectBuilder.build(GerritProjectBuilder.java:39)
[SonarQube] 	at org.sonar.batch.scan.ProjectBuildersExecutor.execute(ProjectBuildersExecutor.java:49)
[SonarQube] 	at org.sonar.batch.scan.ImmutableProjectReactorProvider.provide(ImmutableProjectReactorProvider.java:32)
[SonarQube] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[SonarQube] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[SonarQube] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[SonarQube] 	at java.lang.reflect.Method.invoke(Method.java:498)
[SonarQube] 	at org.picocontainer.injectors.MethodInjector.invokeMethod(MethodInjector.java:129)
[SonarQube] 	at org.picocontainer.injectors.MethodInjector.access$000(MethodInjector.java:39)
[SonarQube] 	at org.picocontainer.injectors.MethodInjector$2.run(MethodInjector.java:113)
[SonarQube] 	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
[SonarQube] 	at org.picocontainer.injectors.MethodInjector.decorateComponentInstance(MethodInjector.java:120)
[SonarQube] 	at org.picocontainer.injectors.CompositeInjector.decorateComponentInstance(CompositeInjector.java:58)
[SonarQube] 	at org.picocontainer.injectors.Reinjector.reinject(Reinjector.java:142)
[SonarQube] 	at org.picocontainer.injectors.ProviderAdapter.getComponentInstance(ProviderAdapter.java:96)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
[SonarQube] 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:67)
[SonarQube] 	... 35 more
[SonarQube] Caused by: com.jcraft.jsch.JSchException: java.io.FileNotFoundException: /home/jenkins/.ssh/known_hosts (No such file or directory)
[SonarQube] 	at com.jcraft.jsch.KnownHosts.setKnownHosts(KnownHosts.java:63)
[SonarQube] 	at com.jcraft.jsch.JSch.setKnownHosts(JSch.java:303)
[SonarQube] 	at fi.jpalomaki.ssh.jsch.JschSshClient.newSessionFor(JschSshClient.java:87)
[SonarQube] 	at fi.jpalomaki.ssh.jsch.JschSshClient.executeCommand(JschSshClient.java:74)
[SonarQube] 	... 55 more
[SonarQube] Caused by: java.io.FileNotFoundException: /home/jenkins/.ssh/known_hosts (No such file or directory)
[SonarQube] 	at java.io.FileInputStream.open0(Native Method)
[SonarQube] 	at java.io.FileInputStream.open(FileInputStream.java:195)
[SonarQube] 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[SonarQube] 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
[SonarQube] 	at com.jcraft.jsch.KnownHosts.setKnownHosts(KnownHosts.java:59)
[SonarQube] 	... 58 more

If not hostkey in known_hosts. we'll get 
[SonarQube] 08:55:15.775 DEBUG: Executing command 'gerrit review 7675590f782b5042674fdabd6b7e2da62f98ac4b -j' on UserAtHost@1a1ed4e5 [user=xxx, host=xxxx, port=29418] (stdin = 69 bytes)
[SonarQube] 08:55:15.998 INFO: ------------------------------------------------------------------------
[SonarQube] 08:55:15.998 INFO: EXECUTION FAILURE
[SonarQube] 08:55:15.998 INFO: ------------------------------------------------------------------------
[SonarQube] 08:55:15.998 INFO: Total time: 14.863s
[SonarQube] 08:55:16.070 INFO: Final Memory: 58M/617M
[SonarQube] 08:55:16.070 INFO: ------------------------------------------------------------------------
[SonarQube] 08:55:16.070 ERROR: Error during SonarQube Scanner execution
[SonarQube] java.lang.IllegalStateException: Unable to load component class org.sonar.batch.scan.ImmutableProjectReactor
[SonarQube] 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:69)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
[SonarQube] 	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
[SonarQube] 	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
[SonarQube] 	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
[SonarQube] 	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
[SonarQube] 	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
[SonarQube] 	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
[SonarQube] 	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
[SonarQube] 	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
[SonarQube] 	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
[SonarQube] 	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.instantiateComponentAsIsStartable(DefaultPicoContainer.java:1034)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.addAdapterIfStartable(DefaultPicoContainer.java:1026)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1003)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
[SonarQube] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:141)
[SonarQube] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
[SonarQube] 	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
[SonarQube] 	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
[SonarQube] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
[SonarQube] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
[SonarQube] 	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
[SonarQube] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
[SonarQube] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
[SonarQube] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[SonarQube] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[SonarQube] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[SonarQube] 	at java.lang.reflect.Method.invoke(Method.java:498)
[SonarQube] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[SonarQube] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
[SonarQube] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
[SonarQube] 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
[SonarQube] 	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
[SonarQube] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
[SonarQube] 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
[SonarQube] Caused by: fi.jpalomaki.ssh.SshClientException: Failed to execute command 'gerrit review 7675590f782b5042674fdabd6b7e2da62f98ac4b -j' on UserAtHost@1a1ed4e5 [user=xxx, host=xxxx, port=29418]
[SonarQube] 	at fi.jpalomaki.ssh.jsch.JschSshClient.executeCommand(JschSshClient.java:77)
[SonarQube] 	at fr.techad.sonar.gerrit.GerritSshConnector.setReview(GerritSshConnector.java:56)
[SonarQube] 	at fr.techad.sonar.gerrit.GerritSshFacade.setReview(GerritSshFacade.java:46)
[SonarQube] 	at fr.techad.sonar.GerritProjectBuilder.build(GerritProjectBuilder.java:39)
[SonarQube] 	at org.sonar.batch.scan.ProjectBuildersExecutor.execute(ProjectBuildersExecutor.java:49)
[SonarQube] 	at org.sonar.batch.scan.ImmutableProjectReactorProvider.provide(ImmutableProjectReactorProvider.java:32)
[SonarQube] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[SonarQube] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[SonarQube] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[SonarQube] 	at java.lang.reflect.Method.invoke(Method.java:498)
[SonarQube] 	at org.picocontainer.injectors.MethodInjector.invokeMethod(MethodInjector.java:129)
[SonarQube] 	at org.picocontainer.injectors.MethodInjector.access$000(MethodInjector.java:39)
[SonarQube] 	at org.picocontainer.injectors.MethodInjector$2.run(MethodInjector.java:113)
[SonarQube] 	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
[SonarQube] 	at org.picocontainer.injectors.MethodInjector.decorateComponentInstance(MethodInjector.java:120)
[SonarQube] 	at org.picocontainer.injectors.CompositeInjector.decorateComponentInstance(CompositeInjector.java:58)
[SonarQube] 	at org.picocontainer.injectors.Reinjector.reinject(Reinjector.java:142)
[SonarQube] 	at org.picocontainer.injectors.ProviderAdapter.getComponentInstance(ProviderAdapter.java:96)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
[SonarQube] 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
[SonarQube] 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:67)
[SonarQube] 	... 35 more
[SonarQube] Caused by: com.jcraft.jsch.JSchException: reject HostKey: gerrit.app.alcatel-lucent.com
[SonarQube] 	at com.jcraft.jsch.Session.checkHost(Session.java:771)
[SonarQube] 	at com.jcraft.jsch.Session.connect(Session.java:342)
[SonarQube] 	at fi.jpalomaki.ssh.jsch.JschSshClient.newSessionFor(JschSshClient.java:94)
[SonarQube] 	at fi.jpalomaki.ssh.jsch.JschSshClient.executeCommand(JschSshClient.java:74)
[SonarQube] 	... 55 more

**Comment by mildis** [comment]
Hi,

A patch is currently being reviewed.
If the known_hosts file exists and is no empty => use it and enable StrictHostKeyChecking
If the known_hosts file exists but is empty => disable StrictHostKeyChecking
If the known_hosts file does not exists => create it and disable StrictHostKeyChecking

**Comment by mildis** [comment]
Which version of SonarQube are you using ? (to know on which branch I should cherry-pick the commit to)

**Comment by egorse** [comment]
@mildis  btw - which version should be used for SQ 7.0 ?

**Comment by mildis** [comment]
Latest release should work with 7.0 but does not include PR #43 for StrictHostKeyChecking
https://github.com/tech-advantage/sonar-gerrit-plugin/releases/latest

**Comment by egorse** [comment]
Added #45

**Comment by mildis** [comment]
Solved
