### ISSUE TITLE
which is the difference between this plugin and the jenkins"sonar gerrit plugin "

### ISSUE THREAD

**Issue by ontheway01** [tech-advantage/sonar-gerrit-plugin#49]
thanks for this plugin.but when I use ,i have two questions .
firstly,I can not find "Log in as admin, Manage Jenkins - Configure System - Sonar - Advanced".Should I install the sonar plugin in the Jenkins  first?
then,I find the two plugins related the sonar geerit, the this one is yours,the other is  jenkin's plugin:https://github.com/aquarellian/sonar-gerrit-plugin.when i use posting SonarQube issues as Gerrit review comments,the two plugins are all needed to be installed.

**Comment by mildis** [comment]
Hi,

This plugin is meant to be installed in SonarQube server.
It makes SonarQube pushes results to Gerrit, whether analysis has been submitted by hand, by Jenkins or any other CI tool.

Aquarellian's plugin is a client-side plugin to be installed into Jenkins which pushes results of an analysis ran with Jenkins to Gerrit.

**Comment by ontheway01** [comment]
Thank you very much.But
