### ISSUE TITLE
Do you not support ldap login？

### ISSUE THREAD

**Issue by heanping** [tech-advantage/sonar-gerrit-plugin#67]
Hi,

Gerrit has integrated ldap login, but can this plug-in only be HTTP? Can I support ldap login? How can I set it?

**Comment by mildis** [comment]
Hi,

The plugin act as any other gerrit client : you can set it to connect either using ssh or http.  
If gerrit is set to authenticate your users with LDAP, then LDAP auth will be used with the http credentials provided.

**Comment by heanping** [comment]
> Hi,
> 
> The plugin act as any other gerrit client : you can set it to connect either using ssh or http.
> If gerrit is set to authenticate your users with LDAP, then LDAP auth will be used with the http credentials provided.

Hi,

Thank you for your reply. May I ask if the following error message should be resolved? There is something wrong with Gerrit configuration, but I have checked it for a long time and failed to solve it.

--------------------------------------------------------------------------------------------------
14:24:52.135 ERROR: [GERRIT PLUGIN] ReviewConfiguration is not valid : GerritConfiguration [valid=false, enabled=true, scheme=http, host=10.16.3.10, port=8081, anonymous=false, username=sonar, password=*obfuscated*, authScheme=basic, basePath=/, sshKeyPath=~/.ssh/id_rsa, label=Verified, message=Sonar review at ${sonar.host.url}, issueComment=[${issue.isNew}] New: ${issue.ruleKey} Severity: ${issue.severity}, Message: ${issue.message}, threshold=MAJOR, voteNoIssue=1,voteBelowThreshold=1,voteAboveThreshold=-1,commentNewIssuesOnly=true, projectName=null, branchName=null, changeId=null, revisionId=null]

**Comment by mildis** [comment]
```projectName=null, branchName=null, changeId=null, revisionId=null```  
These values should not be null.  
You should call SQ with these parameters defined.  

Something like ```-DGERRIT_PROJECT=${GERRIT_PROJECT} -DGERRIT_BRANCH=${GERRIT_BRANCH} -DGERRIT_CHANGE_ID=${GERRIT_CHANGE_ID} -DGERRIT_PATCHSET_REVISION=${GERRIT_PATCHSET_REVISION}```  

With Jenkins for example, theses parameters are set by the Gerrit Trigger plugin.

**Comment by heanping** [comment]
> `projectName=null, branchName=null, changeId=null, revisionId=null`
> These values should not be null.
> You should call SQ with these parameters defined.
> 
> Something like `-DGERRIT_PROJECT=${GERRIT_PROJECT} -DGERRIT_BRANCH=${GERRIT_BRANCH} -DGERRIT_CHANGE_ID=${GERRIT_CHANGE_ID} -DGERRIT_PATCHSET_REVISION=${GERRIT_PATCHSET_REVISION}`
> 
> With Jenkins for example, theses parameters are set by the Gerrit Trigger plugin.

Hi, thank you.
However, I finally reported an error. I don't know how to deal with this error. Could you please help me check the log below? Thank you again

22:44:15.408 INFO: [GERRIT PLUGIN] Entity : )]}'
{
  "labels": {
    "Code-Review": 1
  }
}

22:44:15.411 INFO: Task total time: 5.745 s
22:44:15.486 INFO: ------------------------------------------------------------------------
22:44:15.486 INFO: EXECUTION SUCCESS
22:44:15.486 INFO: ------------------------------------------------------------------------
22:44:15.486 INFO: Total time: 6.701s
22:44:15.539 INFO: Final Memory: 13M/57M
22:44:15.539 INFO: ------------------------------------------------------------------------
22:44:15.539 DEBUG: Connection manager is shutting down
22:44:15.539 DEBUG: http-outgoing-0: Close connection
22:44:15.540 DEBUG: Connection manager shut down
WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succeeded?
WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succeeded?
Getting Sonar Report from: /home/jenkins/workspace/sonar_test/.scannerwork/sonar-report.json
Report has loaded and contains 0 issues
ERROR: Build step failed with exception
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
	at org.jenkinsci.plugins.sonargerrit.SonarToGerritPublisher.perform(SonarToGerritPublisher.java:112)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1840)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Post SonarQube issues as Gerrit comments' marked build as failure
Finished: FAILURE

**Comment by mildis** [comment]
The error is triggered by @aquarellian plugin forked by JenkinsCI at https://github.com/jenkinsci/sonar-gerrit-plugin
`org.jenkinsci.plugins.sonargerrit.SonarToGerritPublisher` is not part of our plugin.
